public_gsheets_url = "https://docs.google.com/spreadsheets/d/1-iXD_P4F_9x2rTUcgR1Hi0G5nvuoo527r3Zc6GvT5vY/edit?usp=sharing"
venezia_gsheets_url = "https://docs.google.com/spreadsheets/d/1dVD9jfc0zBoK_4YExxI-VmRmviVkJ8AA/edit?usp=sharing"
gol_gsheets_url = "https://docs.google.com/spreadsheets/d/11cQFt-kml7FzOTBlG0n5eNbJNDr_9PQ0/edit?usp=sharing"
